version: "3.8"
services: 
  client:
    image: deep-learning-workstation:5000/react-template:edge
    networks:
      - public 
    build: 
      context: .
      dockerfile: Dockerfile.edge
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == xavier-nx-edge]
    ports:
      - "3000:3000"
      

networks:
  public:
    external: true
    name: public
