version: "3.8"
services: 
  client:
    image: react-template
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ".:/app:rw"
      - "/app/nodemodules"